version: "3.9"
services:
  rag:
    image: rag:latest
    build:
      dockerfile: rag.Dockerfile
    container_name: rag
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./documents:/home/strokmatic/documents"
    environment:
      - CODES=
      - DOCUMENTS=./documents
      - WEBSITES=https://www.hikrobotics.com/en/machinevision/visionproduct?typeId=78&id=145,https://www.baslerweb.com/en/cameras/#produkte
      - MODEL=llama3
      - CHUNK_SIZE=4000
      - CHUNK_OVERLAP=2000
      - DESCRIPTION=Ask a Question!
      - PLACEHOLDER=Quais as cameras mais rapidas disponíveis?...
      - TITLE=GPT-Vision
    restart: always
    network_mode: host
